### ISSUE TITLE
[request] Examples

### ISSUE THREAD

**Issue by DarthWound** [p-e-w/argos#10]
Hello, thank you very much for this awesome extension, it's replacing almost all the other ones I've used.

However I would like to know if you could provide scripts from your screenshots, to take inspiration from them, should be useful for me but for a lot of people too I guess.

_...and I have to rtfm in order to make python menus like the "applications" one :p_

Greatest GS' extension without a doubt, keep up the good work!

**Comment by p-e-w** [comment]
Have you seen the ["Examples" section in the README](https://github.com/p-e-w/argos#examples)? Every screenshot there is actually accompanied by the source code of the script.

**Comment by DarthWound** [comment]
Yes, sorry I meant these ones, in the very first animated image:
https://cloud.githubusercontent.com/assets/2702526/21953508/7463004c-da5f-11e6-99e1-b8db1167c071.gif

**Comment by daroczig** [comment]
I'd also love to see eg the `bandwidth.1s.py` from there

**Comment by p-e-w** [comment]
Sorry to have to disappoint you both... those scripts don't actually exist. They were simply Python two-liners that output random numbers for the purpose of making an interesting screencast. I implemented none of the suggested functionality (the email senders kind of give that away...).

That being said, it is definitely possible to create all these scripts for real. The [BitBar plugins repository](https://github.com/matryer/bitbar-plugins) has many similar scripts that actually work.
