### ISSUE TITLE
Menu broken with gjs 1.58.2

### ISSUE THREAD

**Issue by LanderN** [p-e-w/argos#101]
I just updated gjs on my system to 1.58.2 (from 1.58.1) and my argos extensions stopped working properly.

They still show the title on the top bar, but clicking on them does not trigger the menu.

Minimum reproducible case:
```python
#! /usr/bin/python3

print("Title")
print("---")
print("Menu item")
```

This shows "Title" in the top bar, but does not show "Menu item" when clicking on "Title".

**Comment by zurchpet** [comment]
I can confirm. I have the same issue since I've updated gjs to 1.58.2.

**Comment by zurchpet** [comment]
It works again after the update to gjs 1.58.3 today.

Can be closed.
