### ISSUE TITLE
Argos does not work any longer with gnome 3.36.2 ?

### ISSUE THREAD

**Issue by LaurentOngaro** [p-e-w/argos#116]
Do you have any issue to run Argos on the last gnome version (3.36.2 updated the 1st of may) ? Because It it does not work any longer for me. 
I run the last version on gnome 3.6.1 with only small issues, but now, it's broken

The debug log says that  the line #17 of menuitem.js
`const AltSwitcher = imports.ui.status.system.AltSwitcher;` 
is causing an issue.

In the gnome extension API source code I saw that  AltSwitcher has been removed from the ui.status.system module

So it seems normal that this change broke the extension.
I've tried to fix that , but the changes to make exceed my knowledge of the gnome extension API.

I'm trying to create another "compatible" extension using Argos code , but it will be long because I don't really know the gnome extension API, and the docs and examples are really messy

**Comment by insign** [comment]
Please, check #114

**Comment by LaurentOngaro** [comment]
@insign , I've already check this thread
It didn't worked for me
The code still contains the `AltSwitcher` usage 

In the gnome API source of the system module ,
[https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/status/system.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/status/system.js)
AltSwitcher has been removed.

So I can't understand how this code can work with the last version of the API

Do you test it with 3.36.2 version ? 
Does it work ? 
If so, Where could I be wrong ?
