### ISSUE TITLE
Add to AlternativeTo

### ISSUE THREAD

**Issue by mmuman** [p-e-w/argos#12]
[AlternativeTo](http://alternativeto.net/) is a website listing alternatives to software. Argos should be mentioned as an alternative to [BitBar](http://alternativeto.net/software/bitbar/).

**Comment by mmuman** [comment]
Just added [Argos](http://alternativeto.net/software/argos/) and it's been approved. Feel free to submit fixes to it.

**Comment by p-e-w** [comment]
Thanks!
