### ISSUE TITLE
Repo For Argos modded scripts

### ISSUE THREAD

**Issue by Hippyjake** [p-e-w/argos#13]
# https://argos-scripts.github.io
We have a site.
# Add your Argos Scripts here!
Leave a comment and I'll update this post with your links to comments, repos and gists.

# Users!
[Click here to search Github for scripts!](https://github.com/search?utf8=✓&q=argos+gnome&type=)

# Authors
Add tags to your repos so users have a better chance of finding your scripts. Use "gnome-shell" or "gnome" and "argos"

### System Monitor
https://github.com/fadeouter/sysinfo

### Network Monitor
https://github.com/p-e-w/argos/issues/13#issuecomment-296490068

### Stock Quotes
https://github.com/dfaour/argos-scripts/blob/master/getquotes.py

### Search For Argos Scripts On Github
https://gist.github.com/Jomik/f90a38877363b7d3d4f15df9ea4380d5

### GNOME Shell menu to switch between different PulseAudio sinks
https://gitlab.com/sjohannes/argos-pasink

### GiDeviceInfoMenu for the ideviceinfo tool of libimobiledevice displayed via Bitbar or Argos
https://github.com/BobyMCbobs/GiDeviceInfoMenu

### CPU monitor
https://github.com/luisfpg/argos-scripts#cpu-monitor-cpu1spy

### Memory monitor
https://github.com/luisfpg/argos-scripts#memory-monitor-mem1spy

### Network monitor
https://github.com/luisfpg/argos-scripts#network-monitor-net1spy

### Safeeyes For Argos
https://github.com/fadeouter/safeeyes

### Caffeine Replacement (toggles gnome screensaver)
https://github.com/p-e-w/argos/issues/13#issuecomment-300304939

### Gnome MFA (Google Multi-factor Authentication)
https://github.com/daniperez/gnome-mfa

### Menu of applications you have sandboxed with Firejail
https://github.com/p-e-w/argos/issues/13#issuecomment-301972212

**Comment by Hippyjake** [comment]
Script installation can even be made simple using something like Bitbar has.
https://github.com/matryer/bitbar/blob/master/Scripts/bitbar-bundler

**Comment by fadeouter** [comment]
At least we need a place (reddit thread? google sheet?) where could collect links.

**Comment by p-e-w** [comment]
Given the small user base Argos has at the moment, I'm not sure the overhead of a separate repository is warranted just yet.

If you have scripts to share, why don't you just post them in this issue for now? If a certain number of Argos-specific scripts accumulate this way, we can move them to a more suitable place eventually.

**Comment by WhiteheadV** [comment]
Okay then, the following is a simple network/bandwidth monitor script.
It uses [bwm-ng](https://github.com/vgropp/bwm-ng) which should be the only dependency.
```bash
#!/bin/bash

outp=$(bwm-ng -o csv -C ' ' -c 1 | grep eth0 | awk '{printf "%d %d", $3, $4}')
                    #name of the interface^ you want or 'total' 4 all
up=${outp% *}
dl=${outp#* }
dunit="Bps"
uunit="Bps"

if [ $dl -ge 1000 ] && [ $dl -le 1000000 ]; then
  dunit="KBps"
  dl=$(echo "$dl" | awk '{printf("%d",$1 / 1000 + 0.5)}') # (((rounding)))
elif [ $dl -ge 1000000 ]; then
  dunit="MBps"
  dl=$(echo "$dl" | awk '{printf("%d",$1 / 1000000 + 0.5)}')
fi
if [ $up -ge 1000 ] && [ $dl -le 1000000 ]; then
  uunit="KBps"
  up=$(echo "$up" | awk '{printf("%d",$1 / 1000 + 0.5)}') # (((rounding)))
elif [ $up -ge 1000000 ]; then
  uunit="MBps"
  up=$(echo "$up" | awk '{printf("%d",$1 / 1000000 + 0.5)}')
fi

drop=$(bwm-ng -o plain -c 1 | head -n 10 | tail -n 7 | awk '{ORS="\\n"};1')

socketstat=$(ss -s | awk '{ORS="\\n"};1') # ⇡ ⇣ ⇃ ↾

echo "<big>⇣</big>$dl<small>$dunit</small><big></big><big>⇡</big>$up"\
"<small>$uunit</small> | font=monospace size=8 color=#33BEFF refresh=true"
echo "---"
echo "$drop | size=10 font=monospace trim=false bash='bwm-ng; touch $0'"
echo "---"
echo "$socketstat | size=10 font=monospace | bash='ss | less'" # ss -a -A udp
```

**Comment by fadeouter** [comment]
So, this is my "System monitor" script and it uses SVG to draw bars and pie charts. Realtime graph in further plans.
[](https://github.com/fadeouter/sysinfo)

**Comment by dfaour** [comment]
Script to show stock quotes:

https://github.com/dfaour/argos-scripts/blob/master/getquotes.py

**Comment by Hippyjake** [comment]
Hey check this out. https://github.com/search?utf8=✓&q=argos+gnome&type=

I'll contact the authors and see if I can link them here.
A wiki page might bee a good Idea.

**Comment by Jomik** [comment]
@Hippyjake Made it a python script, click the name to open the repo in your browser.

```
#!/usr/bin/env python3

import requests
import json

r = requests.get(url='https://api.github.com/search/repositories?q=argos+gnome&order=desc')
data = r.json()

print("Argos Search\n---")
for item in data["items"]:
    print(item["name"] + " | href=" + item["html_url"])
```

**Comment by Hippyjake** [comment]
@Jomik Amazing work!

**Comment by Jomik** [comment]
> Script installation can even be made simple using something like Bitbar has.
> https://github.com/matryer/bitbar/blob/master/Scripts/bitbar-bundler

https://gist.github.com/Jomik/0a3de172bc2f7ee9f17ae97a324077a7

**Comment by Hippyjake** [comment]
Dang @Jomik It would have taken me a week to do that!

**Comment by fadeouter** [comment]
My analog of Safeyes: https://github.com/fadeouter/safeeyes
For authors may be interesting how I implemented disable/enable script feature.

**Comment by lacereation** [comment]
This toggles the gnome screensaver.  It's the only thing ever to work for me incl. Caffeine.  I wrote it for a desktop.  There is also an unplugged setting for Notebooks, so it may not be the complete solution for Notebooks.

keep-awake.2s.sh

```
#!/bin/bash
if [[ $(gsettings get org.gnome.desktop.session idle-delay) == "uint32 0" ]]; then
    i=weather-clear 
else
    i=weather-clear-night 
fi
echo " | iconName=$i"
echo "---"
echo "toggle wakefullness | iconName=$i bash=awake terminal=false"


```
it works with this script
awake

```
#!/bin/bash
# awake with no arg toggles sleep/awake mode for screensaver
# awake 1 # keeps awake
# awake 0 # allows screensaver activation
idleDelay=720 #12 mins.
if [[ $1 == 0 ]]; then
    if [[ $(gsettings get org.gnome.desktop.session idle-delay) == "uint32 0" ]]; then
        gsettings set org.gnome.desktop.session idle-delay $idleDelay 
        gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout $idleDelay
        fi
elif [[ $1 == 1 ]]; then
    if [[ $(gsettings get org.gnome.desktop.session idle-delay) == "uint32 $idleDelay" ]]; then
        gsettings set org.gnome.desktop.session idle-delay 0 
        gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
    fi
elif [[ $(gsettings get org.gnome.desktop.session idle-delay) == "uint32 0" ]]; then
    gsettings set org.gnome.desktop.session idle-delay $idleDelay 
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout $idleDelay
else
    gsettings set org.gnome.desktop.session idle-delay 0 
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0      
fi

```

**Comment by daniperez** [comment]
nice work 👍 ! 

I created a Google Authenticator -like app to manage OTP/MFA tokens:

https://github.com/daniperez/gnome-mfa

![mfa](https://github.com/daniperez/gnome-mfa/raw/master/mfa.png)

Feedback welcome!

**Comment by filchermcurr** [comment]
I have absolutely no idea what I'm doing Bash-wise, so here's my attempt at showing a menu of applications you have sandboxed with Firejail. Theoretically clicking on an entry in the menu will open a terminal inside of the sandbox. It's not very useful, but it was a fun learning experience!

![image](https://cloud.githubusercontent.com/assets/11351104/26136555/702c8f7e-3a82-11e7-9802-ed6b3ae6a113.png)

```
#!/bin/bash

list=$(firejail --list | grep -v "firejail --list")
# wc -l will apparently interpret the blank variable as 1, which is undesirable!
if [ -z "$list" ]; then
    jail="0"
else
    jail=$(echo "$list" | wc -l)
fi
echo "<span color='yellow'>🛡️</span>: $jail"
echo "---"
if [ -z "$list" ]; then
    echo "No sandboxed applications running."
else
echo "Sandboxed Applications | size=12"
for x in $list
do
    xpid=$(echo "$x" | awk '{s=index($1,":"); print substr($1, 1, s-1);}')
    if [ "$xpid" != "" ]; then
        printpid="$xpid"
    fi
    if [ -e "$x" ]; then
 	filename="${x##*/}"
    # Icon overrides for those pesky things that don't work quite right.
    if [ "$filename" == "firefox-bin" ]; then
        iconname="firefox-nightly"
    else
        iconname="$filename"
    fi
    echo "$filename (<span color='orangered'><tt>${printpid}</tt></span>) | iconName=${iconname} bash='firejail --join=${printpid}' terminal=true"
fi
done
fi
echo "----"
echo "Refresh... | refresh=true"

```

**Comment by Hippyjake** [comment]
So I did a thing guys.

https://argos-scripts.github.io

The source is https://github.com/argos-scripts. Forked from the Fisherman site. What do you all think?

**Comment by fadeouter** [comment]
hey people, check out the new version of sysinfo script (https://github.com/fadeouter/sysinfo)
i did many impovements in svg drawing part and CPU calculation
i'll be appreciate for any feedback 
also, now im in work with this one: http://i.imgur.com/8djJQtE.png
SVG is amazing!

**Comment by bluespy** [comment]
This is interesting stuff.
I checked out https://argos-scripts.github.io and it still seems needs a lot of touch.
Is there any plan to continue on that site? As for now, even the links are still going to Fisherman site.

**Comment by Hippyjake** [comment]
@bluespy Yes I have not had much time to work on it. Are you good at Javascript? Cause im not ha. If you want we can move this conversation to the site repo. The javascript is having a parsing error reading the index file.

**Comment by marksev1** [comment]
Could you guys help me do like a launcher for "launching" MQTT commands  and also for displaying sensor values received with MQTT (mosquitto)? Like home-automation type stuff. I think it would be a cool demo of the power of the extensions since IOT is now a hot topic. :)

**Comment by mmuman** [comment]
Ok let's put mine as well…

# [Emacs Buffers: emacs.sh](https://github.com/mmuman/my-argos-scripts#emacs-buffers-emacssh)
Lists the buffers in running Emacs (you need to have Emacs-Server enabled) and goes right to the selected one.

# [Freeze processes: freeze.sh](https://github.com/mmuman/my-argos-scripts#freeze-processes-freezesh)
Lists the top processes and allows freezing them, and unfreezing as well.
This helps when, say, Firefox eats up too much RAM and you want to leave it swapped out when working on something else.

# [Silkaj: silkaj.10m.sh](https://github.com/mmuman/my-argos-scripts#silkaj-silkaj10msh)
Silkaj is a python command line client for the DUniter blockchain-based P2P Fair Money system.
I added an "argos" command to Silkaj, so this script just runs it with the command as argument.

# [VirtualBox VMs: virtualbox.sh](https://github.com/mmuman/my-argos-scripts#virtualbox-vms-virtualboxsh)
Lists the VirtualBox virtual machines, and allows changing their state.

**Comment by fadeouter** [comment]
Finally, ou can try my extension for Weather: https://github.com/fadeouter/argosWeather
<img src="https://github.com/fadeouter/argosWeather/raw/master/screenshot.png" width="200">

**Comment by Hippyjake** [comment]
@fadeouter @mmuman Your scripts have been added to https://argos-scripts.github.io!

**Comment by p-e-w** [comment]
@fadeouter: That weather extension is... amazing. I am awed by your SVG wizardry!

A quick note to the "Argos community": Although there hasn't been an update in a while, Argos is most definitely *not* abandoned, and I am planning to make some small tweaks soon, as well as possibly add some new features later.

Also, in the future, Argos will be even more awesome than it is today, because **color emoji support has landed in the GNOME stack!!!!!** This means that any number of multicolor icons can be inlined in menu items by referencing their name and might allow scripts like the weather extension above to be dramatically simplified at some point.

**Comment by domsle** [comment]
My little snippet, that lets you control external monitors brightness via DDC/CI (most HDMI) here, just insert it into any existing script:
`for VARI in {0..100..5}
do
	echo "$VARI | bash='sudo /usr/bin/ddcutil --bus=2 setvcp 0x10 $VARI' terminal=false"
done`

Required dependancies are: [ddcutil](https://github.com/rockowitz/ddcutil), [i2c-tools](https://github.com/ev3dev/i2c-tools) with i2c_dev module [enabled](https://forum.manjaro.org/t/ddccontrol-not-working-on-manjaro/27513/3?u=domi.nos). 
You also need to add a proper line to your sudoers file, making ddcutil (/usr/bin/ddcutil for me) able to run without password.

After that, you might need to change your --bus=X number to one that ddcutil detect will output, you might as well ignore it but that way it is a bit faster. 

Shame that argos does not support mouse scroll actions/sliders.

**Comment by mmuman** [comment]
Interesting, last time I tried ddcutil it just hanged the kernel, but that was a while ago...

**Comment by mmuman** [comment]
As for sliders, I'm quite sure argos would accept patches to support that (and the native slider control would likely handle mouse wheel directly). Would be nice to agree with BitBar on the syntax though.

**Comment by OccamsQuattro** [comment]
https://github.com/OccamsQuattro/ws_time_tracker
This is a time tracking service aimed at freelancers and consultants with gnome shell integration using Argos.

**Comment by p-e-w** [comment]
I have opened up the Wiki for editing. The Wiki is now the official place for listing Argos plugins; please add your plugins there.

**Comment by daniperez** [comment]
first plugin added to wiki :laughing:

**Comment by p-e-w** [comment]
Dear friends of Argos,

in the past weeks I have fixed some long-standing issues and added new capabilities to Argos (see the commit log for details). I intend to submit an update to extensions.gnome.org soon, but would like some confirmation first that everything still works as expected, particularly on older versions of GNOME Shell.

If you have a few minutes to spare, you would help me greatly by [manually installing the latest Argos](https://github.com/p-e-w/argos#manually) from master and testing your plugins, then dropping a quick comment with the result in this thread, mentioning your GNOME Shell version.

Thanks!

**Comment by fadeouter** [comment]
Hi! Tested the new version. All my scripts working fine, noticed better placement of the pop-up menus. Thanks for update!

**Comment by mmuman** [comment]
Seems to work here on a mixture of 3.22 and 3.26. 
gnome-shell 3.22.3-3 (but control panel says 3.26.2 !?)
gjs 1.46.0-1+b2
libgjs0e 1.46.0-1+b2

**Comment by iSonik** [comment]
Made a little power draw info tool :)
https://github.com/iSonik/SimpleWattage-Argos

**Comment by mmuman** [comment]
> Made a little power draw info tool :)
> https://github.com/iSonik/SimpleWattage-Argos

Nice!

I'd use W as suffix though, as it's the unit (Watt), the quantity measured being the power. Btw, some machines have multiple batteries ;-)

**Comment by iSonik** [comment]
Oh thx. Yeah multiple batteries would have been my next step, and yeah the "done" was an leftover :p oops!
You wrote on my Github page:
; if [ "$Wattage" = 0 ]; then
	echo "🗲🔌\n"

So i assume your laptop shows 0 Watt when plugged to the wall? Because my still shows a number. Like  (35. the max TDP Wattage which my Laptop jumps to.

Its my first project ever on linux! So i pardon my mistakes :)

**Comment by mmuman** [comment]
> So i assume your laptop shows 0 Watt when plugged to the wall? Because my still shows a number. 

Only when it has stopped charging actually.

**Comment by iSonik** [comment]
Yeah i fixed that with an update :) has quite some features now

**Comment by mmuman** [comment]
Btw, until you actually push newer commits it's still possible to rewrite them, specially those "update readme" ones, you can squash them, or just commit --amend with new changes ;-)

**Comment by iSonik** [comment]
Great input again! Thx. 

I currently have an idea to fix the problem with multiple batteries, but i cannot test it since my Mi Laptop has only one (arent multiple batteries quite rare anyways?) Does your laptop have 2 batteries?

Regarding tail. Is it really that bad?
for b in /sys/class/power_supply/BAT*; do
	read mV < "$b/device/power_supply/${b##*/}/voltage_now"
	mA=0

I just  removed the Force Black Icon :)

**Comment by kmeehl** [comment]
https://github.com/kmeehl/argos-firefox-profile-launcher

This Argos extension finds and lists all Firefox profiles, to make it convenient to launch them.

**Comment by plegrand1** [comment]
RSS Reader

i adapted this script "https://github.com/akras14/eznews/blob/master/index.php" to make it works on argos




[RSS.txt](https://github.com/p-e-w/argos/files/3729481/RSS.txt)

**Comment by conf11s3d** [comment]
HELP....!  SCRIPT for Argos   Notify Birthdays in system status area it's possible ?

Hi everyone I used a gnome extension shell "Notify Birthdays" for a very long time and with gnome shell 3.34 stopped working, I tried to contact the author
without success, he abandoned the project.

I kindly ask if possible to create a script for Argos that notifies the birthdays with a small icon and a facsimile of the "Notify Birthdays" extension with notification in system status area https://extensions.gnome.org/extension/687/birthdays_notify/

Thank you all for your kind attention.

**Comment by plegrand1** [comment]
Found on the net : https://easyoradba.com/2019/01/20/having-fun-with-shell-scripting-send-birthday-email-alerts-via-a-shell-script/

Adaptation : 
[birthday.txt](https://github.com/p-e-w/argos/files/3754041/birthday.txt)
[data.txt](https://github.com/p-e-w/argos/files/3754042/data.txt)

I'm not a dev !!! ;-)
icon is in base64
you have to rename birthday.txt => birthday.sh
                                  data.txt => data
put the right path of data file
it works on my PC
good luck

**Comment by conf11s3d** [comment]
Thank you so much as soon as I get home I'll try the script thanks a lot ....

**Comment by Skillzore** [comment]
I have made a Spotify extension. https://github.com/Skillzore/argosSpotifyExtension
It has been on the wiki for a while, would be nice to have it searchable on https://argos-scripts.github.io as well :)

**Comment by Hippyjake** [comment]
@Skillzore i've added it!

**Comment by FedderSan** [comment]
Hi 
I'm on popos 20, and I have it installed, but I do not see the dropdowns.
I have tried making simplescripts with dum
"
#!/usr/bin/env bash

echo "TEST"
echo "---"
echo "TEST"
"
But I dont get a dropdown, only the "TEST" title on the top bar.
I have tried taking already made scripts, but none will do the trick.
If I write some random characters in the top like
"
dag
#!/usr/bin/env bash

echo "TEST | dropdown=true"
echo "---"
echo "TEST"
" 
It gives me a dropdown but only of the script name "Test.sh"
