### ISSUE TITLE
Sub Menues not working

### ISSUE THREAD

**Issue by hobbypunk90** [p-e-w/argos#14]
You say in your readme it is a problem with gnome 3.22, but i don't think so. on Gnome 3.24 its also not working 😉
i used the [Connection Manager](https://github.com/Silarn/connectionmanager2) for a long time and it works with submenues and subsubmenues.

the only problem i see in argos is, that the parent menu closes when i try to open the child.
i hope you can fix it soon 🙂

**Comment by Hippyjake** [comment]
I think is means starting from 3.22 and up, sub-menus don't work.
I do wish they did tho!
Good test is https://getbitbar.com/plugins/Tutorial/submenus.sh

**Comment by hobbypunk90** [comment]
i see, but in other extensions submenus works, it looks like this:
![Connection Manager](https://cloud.githubusercontent.com/assets/3696730/24969325/b64df7be-1fb0-11e7-954b-6380a1ea59d3.png)

the readme sounds like its a bug in gnome shell

**Comment by Hippyjake** [comment]
The sub menu issue, I'm guessing is related to the way Argos runs and renders scripts, not the Shell it self (well some API changes have broke many extentions in the past). Just a guess tho

**Comment by p-e-w** [comment]
> You say in your readme it is a problem with gnome 3.22, but i don't think so. on Gnome 3.24 its also not working 😉

Here's what the README actually says (emphasis added):

> While Argos supports nested submenus *in principle*, GNOME Shell does not render them correctly **as of version 3.22.**

What this means is that GNOME Shell 3.22 does not support nested submenus. Nowhere is it claimed that later versions do, and indeed as you have found they do not.

This is a bug/limitation in GNOME Shell and has nothing to do with how Argos renders menu items. As noted [here](https://github.com/p-e-w/argos/issues/6#issuecomment-287654940), it can be worked around with monkey patching, but I have no intention of doing that.
