### ISSUE TITLE
Gnome 45 compatibility

### ISSUE THREAD

**Issue by peterloeffler** [p-e-w/argos#149]
Gnome 45 breaks retro-compatibility with older versions by moving to ESM modules.
In order for argos to run on Gnome >= 45 there are some guidelines to stick to:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

Would be nice to be able to use argos also in the future!

**Comment by mwilck** [comment]
I'll look into this hopefully soon. I've started looking into GNOME 45 for the other extension I'm maintaining, [projecthamster/hamster-shell-extension](https://github.com/projecthamster/hamster-shell-extension).

I think it's doable but not easy. Also, as soon as GNOME 45 support is added, support for all earlier GNOME version must be dropped (this is inevitable this time). So we'll likely need separate branches.

**Comment by mwilck** [comment]
I have pushed my GNOME 45 branch to [WIP-gnome-45](https://github.com/p-e-w/argos/tree/WIP-gnome-45) now. It works ok-ish for me. This branch works **only with GNOME shell 45**.

![Screenshot from 2023-09-26 22-31-44](https://github.com/p-e-w/argos/assets/15961354/d83d904b-b3f4-4542-8820-f7897806de2f)

![Screenshot from 2023-09-26 22-32-43](https://github.com/p-e-w/argos/assets/15961354/4ddeaa4f-a640-44a1-85ba-dde7c62b0bcf)

![Screenshot from 2023-09-26 22-32-09](https://github.com/p-e-w/argos/assets/15961354/d0fc864d-6f38-4911-a9bf-966a8ec09eef)

Please provide feedback.

**Comment by marianrh** [comment]
I tested branch WIP-gnome-45 on the Ubuntu 23.10 beta. In my (simple) use case everything works as expected. Thank you very much for your work!

**Comment by peterloeffler** [comment]
Tested the branch on OpenSUSE Tumbleweed.
For me everything works.
Great! Thanks a lot for your work!

**Comment by ratboy666** [comment]
Testing on Fedora 39 beta. So far, so good. Thanks!

**Comment by Janhouse** [comment]
Seems to work fine. Please consider merging. Arch just switched to Gnome 45, I guess a lot more people will need it.

**Comment by marinierb** [comment]
Works for me on Manjaro unstable.

Thank you so much for this!

**Comment by javadr** [comment]
Thanks @mwilck. Works on Manjaro 23.1.0 Vulcan too. (Gnome 45)

**Comment by Toby-Haynes** [comment]
On Tue, 2023-09-26 at 13:44 -0700, Martin Wilck wrote:
> I have pushed my GNOME 45 branch to WIP-gnome-45 now. It works ok-ish
> for me. This branch works only with GNOME shell 45.
> Please provide feedback.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>
Works nicely for me - thanks for the effort getting this ported. 

Thanks,
Toby Haynes

**Comment by dvogel** [comment]
Works for me on both Debian Trixie and Ubuntu 23.10.

**Comment by Coda-Coda** [comment]
This works for me - thank you very much!!!
On NixOS (unstable channel). Gnome Shell 45.1.

**Comment by nafg** [comment]
Is this going to be mainlined?

**Comment by PaulCrisan** [comment]
Works on Manjaro. Thank you very much!

**Comment by moritz-t-w** [comment]
For the record:
`13. Dec. 2023` [Dario.Lesca](https://extensions.gnome.org/accounts/profile/Dario.Lesca):
> This new version https://github.com/p-e-w/argos/tree/WIP-gnome-45 work on Fedora 39 with Gnome 45.
Also the standard Fedora 39 package "gnome-shell-extension-argos-3^20230404gite2d68ea-3.fc39.noarch" work.

**Comment by moritz-t-w** [comment]
> I think it's doable but not easy. Also, as soon as GNOME 45 support is added, support for all earlier GNOME version must be dropped (this is inevitable this time). So we'll likely need separate branches.

@mwilck I can't find but I read somewhere that you can now publish separate versions on extensions.gnome.org now, in case you didn't already know

**Comment by mwilck** [comment]
> @mwilck I can't find but I read somewhere that you can now publish separate versions on extensions.gnome.org now, in case you didn't already know

That has been possible for years. But we can't publish on extensions.gnome.org.
Have a look at #108, in particular @p-e-w's comments.

Here on GitHub, it's mainly a question which GNOME version the `master` branch should support. The majority of users here would vote for GNOME 45. But it's natural that GNOME 45 users find this issue and #150, whereas users of older GNOME versions (of LTS Linux distros) have no need to raise their voice here. If we merge #150 today, we may get a lot of angry "argos is suddenly broken" reports by these users.

OTOH, GNOME 45 has been released almost 4 months ago, so I guess we shouldn't wait much longer...

**Comment by moritz-t-w** [comment]
Wow that sucks.

**Comment by moritz-t-w** [comment]
Likely related: #155
