### ISSUE TITLE
Allow to draw multiple images in one line and an option to disable image centering

### ISSUE THREAD

**Issue by fadeouter** [p-e-w/argos#16]
I tried to create System monitor script (it's here, if anyone interested in it: https://github.com/fadeouter/sysinfo) and found that it very difficult to draw charts and bars in Argos. It is possible to set height and width for the simple png rectangle, but it always centering. And it's not possible to draw multiple images in one line.

**Comment by p-e-w** [comment]
Do you have a syntax in mind for multiple images in the same line?

**Comment by fadeouter** [comment]
Yes, this is what I keep in mind.

**Comment by p-e-w** [comment]
I have decided not to implement this because it would undoubtedly complicate the code a lot and I only see niche benefits so I don't believe it worth the additional complexity.
