### ISSUE TITLE
Gnome 46 compatibility

### ISSUE THREAD

**Issue by moritz-t-w** [p-e-w/argos#160]
![image](https://github.com/p-e-w/argos/assets/90388353/fe13dcac-cc27-43e4-bd40-cbeedb06c23d)

**Comment by moritz-t-w** [comment]
I really hope that the release of Gnome 46 won't have been the final nail in the coffin for this project.
But at least any extensions made for this will still run in the terminal, which I absolutely love. You can even adopt them to work with xbar. I'm still using my scripts just from the terminal for the time being.

**Comment by Toby-Haynes** [comment]
Have you tried the changes in https://github.com/p-e-w/argos/tree/WIP-gnome-46 ?

**Comment by Toby-Haynes** [comment]
Especially https://github.com/p-e-w/argos/commit/280fe56e6671f190dee40fba3d3209e3d1cfe386

**Comment by hyperair** [comment]
https://github.com/p-e-w/argos/tree/WIP-gnome-46 works for me on Ubuntu 24.04, thanks!

**Comment by moritz-t-w** [comment]
Thanks!
