### ISSUE TITLE
Gnome 46 compatibility

### ISSUE THREAD

**Issue by jd-develop** [p-e-w/argos#162]
Hello :)

I just switched to Gnome 46 and was wondering when the extension will be updated. I see a WIP branch, is it finished?

Thank you,
Jean Dubois

**Comment by rlevitsky** [comment]
I've faced the same issue after upgrading Ubuntu 23.10 to 24.04.

**Comment by rlevitsky** [comment]
I managed to fix this by manually cloning the repo to ~/.local/share/gnome-shell/extensions

**Comment by jd-develop** [comment]
Yep, that fixed the problem! Still, the extension is not updated on the GNOME extensions website, but that is not the point of this issue (so I close it).
