### ISSUE TITLE
Allow refresh from command line

### ISSUE THREAD

**Issue by xhorak** [p-e-w/argos#17]
It would be nice to ask for refresh of specific or all scripts from command line. This could be a workaround for issue #7, imagine as bash="doaction; argos-refresh myscript.10h.sh"

**Comment by xhorak** [comment]
Hm, I just find out workaround for this. Use
`bash="some_user_command; touch $0"`
to reload the script.

**Comment by p-e-w** [comment]
Closing since the underlying issue (#7) has been fixed.
