### ISSUE TITLE
Issue with top viewer

### ISSUE THREAD

**Issue by Jomik** [p-e-w/argos#19]
I'm running GNOME 3.24 and just installed Argos. It doesn't seem to format, or even get the full output... 
![screenshot from 2017-04-29 14-29-07](https://cloud.githubusercontent.com/assets/699655/25555502/4a82feae-2ce8-11e7-99e3-869c8dfa8d08.png)
Removing the awk part of the call makes it better... But formatting is still not proper - doesn't look as good as in the screenshot.
![screenshot from 2017-04-29 14-30-41](https://cloud.githubusercontent.com/assets/699655/25555512/80847c44-2ce8-11e7-9f76-aa0e2bc68d18.png)

**Comment by killown** [comment]
I am having the same issue

**Comment by p-e-w** [comment]
@Jomik: You appear to be using a custom GNOME Shell theme. How does it look with the default theme?

Also, what is the output when running the script in a terminal?

**Comment by Jomik** [comment]
Same issue without the theme.

Here's the output.
![screenshot from 2017-04-29 16-44-16](https://cloud.githubusercontent.com/assets/699655/25556351/213de276-2cfb-11e7-8706-57aeed537e9b.png)

**Comment by killown** [comment]
also top.sh is not refreshing

**Comment by Jomik** [comment]
It -is- refreshing for me. Every 3 seconds. killown, did you call it "top.3s.sh" ? It should update every 3s then. Or "top.1s.sh"

**Comment by killown** [comment]
@Jomik wow didn't about this 1.s thing in the filename, thank you, solved for me

**Comment by WhiteheadV** [comment]
@Jomik try:
```bash
TOP_OUTPUT=$(top -b -n 1 | head -n 20 | tr -d '[]|' | awk '1; {ORS="\\n"}')
echo "$TOP_OUTPUT | font=monospace bash=top"
```

**Comment by Jomik** [comment]
That fixes it @WhiteheadV . Do you mind elaborating? I see the awk call is essentially the same, with less escapes. I'm not familiar with tr though.
I guess it simply deletes all occurences of []| ? Why do we do this here? Is there an issue with argos that makes it so we can't display them? Or is it just because you like that better?

**Comment by fadeouter** [comment]
@Jomik what distro do you use? Can't reproduce this issue on Ubuntu GNOME 17.04 (32-bit).

**Comment by killown** [comment]
![screenshot from 2017-04-30 08-15-56](https://cloud.githubusercontent.com/assets/24453/25563923/695cde36-2d7d-11e7-85d5-2a1f0d44f207.png)

**Comment by Jomik** [comment]
@fadeouter I'm on Arch Linux with Gnome 3.24, 64-bit

**Comment by killown** [comment]
my output is correct now but top.1s.sh is not updating every 1 second

**Comment by Jomik** [comment]
@killown You might want to open that in a new issue 😄

**Comment by p-e-w** [comment]
I just published an updated version of the `top` viewer, but without the fix suggested above. The reason I'm not including this yet is that IMO the real problem here is that those "bar charts" containing the pipe character appear in the output in the first place.

On my system, `top` doesn't show these in the output. Does anyone know under what circumstances these bars are shown (and how to disable them)?
