### ISSUE TITLE
hyperlink from results possible

### ISSUE THREAD

**Issue by olymk2** [p-e-w/argos#22]
The result of one of my commands returns a load of urls, can i make them clickable links some how ?

**Comment by Hippyjake** [comment]
This is an example wrote in python. 
https://gist.github.com/Jomik/f90a38877363b7d3d4f15df9ea4380d5

Check out issue #13 for lots of examples!

**Comment by olymk2** [comment]
Cheers I was trying to make the url with out the pipe adjusted it now.

I will submit this at some point when i have tested it a bit, basically lists docker ips as http urls.

https://gist.github.com/olymk2/fac0e449bc6fb8356846e54deda8f486
