### ISSUE TITLE
Way to accept input from user

### ISSUE THREAD

**Issue by lastweakness** [p-e-w/argos#23]
Hi,  
As of now, is there any way to accept input from user like with StEntry so that when the user clicks enter, we get a new new output from command below it?  
like this:  
```
echo "Tester"
echo "---"
echo (StEntry-Activated-With-Return-Key-or-Enter-Key)
echo (command-using-text-from-StEntry)
```
Is this possible? If not, can it be implemented?  
Thanks

**Comment by p-e-w** [comment]
Yes, it is possible, if slightly tricky:

1. On click, run an external script (`bash` attribute)
2. That script prompts the user for input
3. In response to the input, the script *modifies the Argos plugin script*, e.g. by appending the line you want
4. Argos will detect the modification automatically and reload the plugin

I have no plans to add input handling to Argos itself.
