### ISSUE TITLE
Idea for less CPU load

### ISSUE THREAD

**Issue by StefanTT** [p-e-w/argos#24]
I have a (hopefully) simple idea.

Is it possible to have a commandline parameter that indicates if the dropdown menu is opened?
E.g. a script that runs every some seconds and shows the CPU load in the title.
When opening the dropdown it shows the top 20 processes.

The script could exit after outputting the "---" line if the dropdown is not opened.

**Comment by lacereation** [comment]
Or refresh=true on the line above "---" that would run the script before before the dropdown is displayed?

**Comment by p-e-w** [comment]
This is now possible! See the updated ["`top` viewer"](https://github.com/p-e-w/argos#top-viewer) for an example.

**Comment by StefanTT** [comment]
Great, thank you!
