### ISSUE TITLE
Cinnamon Desktop

### ISSUE THREAD

**Issue by raguay** [p-e-w/argos#25]
Since Cinnamon Desktop is a fork from Gnome 3, will argos work with it? I know the installation process would have to be different since Cinnamon doesn't make use of the ~/.local/share/gnome-shell/extensions path. I'm using Cinnamon with Mint Linux, but I don't know much about using it yet. Just started.

**Comment by p-e-w** [comment]
I have no experience with Cinnamon extensions so I am hoping someone else will answer this.

**Comment by raguay** [comment]
I found argos built in to the sidebar program (forgot the name). I'm experimenting with it.

**Comment by PLanB2008** [comment]
Any progress on this?

**Comment by raguay** [comment]
No. That system died (hardware). I haven't done anything with it since. I mostly use my MacBook Air with macOS. But, Argos does work on Cinnamon Desktop. I didn't get around to using it too much before that system died.

**Comment by groovenectar** [comment]
@raguay Any more info on the sidebar program for Cinnamon, or a tip on where to look?

Here's the official repo of some applets that can be added to the Cinnamon panel:
https://github.com/linuxmint/cinnamon-spices-applets
