### ISSUE TITLE
Taking actions on mouse scroll

### ISSUE THREAD

**Issue by domsle** [p-e-w/argos#26]
It would be lovely to be able to add some additional actions when scrolling over a Argos button. 
The same way as you can change volume then scrolling with mouse hovering over volume icon, or song then mouse is over Media Player Indicator icon.

**Comment by p-e-w** [comment]
I have decided not to implement this as I actually consider scroll actions on a clickable button to be a UX anti-pattern (despite GNOME itself doing this for volume control).
