### ISSUE TITLE
Refresh closes submenus

### ISSUE THREAD

**Issue by beanaroo** [p-e-w/argos#29]
Firstly, amazing extension. Works wonderfully. I have a simple python script that queries the AWS API for all Beanstalk Environment Health Statuses and I can monitor it from a shell menu. I might port it to a native extension as I learn JS.

I noticed that if I have a submenu open and the refresh is invoked, all submenus close. Is this tricky to avoid? I'm guess the state needs to be recorded before a refresh and restored somehow.

**Comment by p-e-w** [comment]
I have come to the conclusion that this isn't a bug after all but the intended behavior. Argos doesn't really *update* the menu on refresh, it recreates it from scratch. The newly created menu can look similar to the previous one, or completely different, or anything in between. Thus there is no state to be preserved across updates, as in general, there is no meaningful way to say that an item or submenu is "the same" as it was before the update.
