### ISSUE TITLE
Command works only if terminal=true

### ISSUE THREAD

**Issue by domsle** [p-e-w/argos#30]
Hey,
When I add an item like this:

`echo "10 | bash='pkexec ddcutil --bus=2 setvcp 0x10 10' terminal=false"`
It will not work, nothing is happening. I need to change terminal=true for it to work.

Why is that?

**Comment by 73** [comment]
### For future reference

Without the `terminal`, it will be a parent of `init` and `pkexec` does not like that.

The solution in simple: Give a parent to `pkexec`:
```
echo "Start sshd | bash='sh -c \"pkexec systemctl start ssh\"' terminal=false"
``` 
Works fine on my workstation.
