### ISSUE TITLE
RangeError: invalid language tag: C

### ISSUE THREAD

**Issue by d97jro** [p-e-w/argos#31]
System monitor has not been working for a while, and I find this in the logs:

gnome-shell[9337]: Extension "system-monitor@paradoxxx.zero.gmail.com" had error: RangeError: invalid language tag: C

I run Debian Testing (Buster) with:

gnome-shell-extension-system-monitor                        33-1
gnome-shell                                                 3.26.2-1
gir1.2-gtop-2.0:amd64                                       2.38.0-1
gir1.2-networkmanager-1.0:amd64                             1.10.0-1

Is there a way where I can make gnome-shell more specifically produce what line in the extension code that causes this?

BR,

/J

**Comment by p-e-w** [comment]
This is not the issue tracker for the system-monitor extension.
