### ISSUE TITLE
custom from list commands as shortcut

### ISSUE THREAD

**Issue by ghost** [p-e-w/argos#32]
Hi,

I would like to custom from list commands as a shortcut, like:

update -y
upgrade
remove
clean
etc

thanks

**Comment by dmitry-saritasa** [comment]
I guess he needs to have custom shell bash commands, sorta launcher. By the way

### FANTASTIC WORK and plugin is GORGEOUS!

**Comment by Hippyjake** [comment]
I think he wants some shell commands to help take care it the installed scripts.

**Comment by p-e-w** [comment]
I still don't understand, and since @dmitry-saritasa's and @Hippyjake's interpretations differ, it seems I'm not the only one. Closing.
