### ISSUE TITLE
Limitation for sudo?

### ISSUE THREAD

**Issue by scoony** [p-e-w/argos#33]
Hi,

I want to make a bash script using sometimes the sudo command (no choice sometime).

Those commands are working fine in terminal but not in Argos.
`echo $password | sudo -S command --arguments > ~/log.txt`
`eval 'echo $password | sudo -S command --arguments' | tee -a ~/log.txt`

even tried to
```
echo "eval 'echo $password | sudo -S command --arguments' | tee -a ~/log.txt" > ~/file.sh
bash ~/file.sh > ~/log.txt
```

Even tried to use the full path of the bin files used ... without any success, the "file.sh" is there and working, the "log.txt" is generated but it remains at 0 byte.

Maybe the sudo command is somehow disabled in Argos...?!?

**Comment by rkmax** [comment]
Well it seems working fine here. I did the following test

```bash
#!/usr/bin/env bash

echo "Test"

echo "---"
echo "Run uptime with sudo | bash='sudo uptime' terminal=false" 
```

if you run the `journalctl /usr/bin/gnome-shell -f` command on a seperate terminal then you can see the output of the command when you click on Test > Run uptime with sudo

**Comment by scoony** [comment]
Normally using when you use the sudo command you need to type your password (this is what prevent the script to run completely in Argos)

You've visudo ?

**Comment by scoony** [comment]
This is why I was wanting to sudo (an extension to check and notify user if any hardware/software issue... and smartctl requires sudo)

![alt text](http://i.imgur.com/UnerUpp.jpg)

**Comment by rkmax** [comment]
I dont know if the `|` make that the command dont run properly, a simple workaround i was I said on my previous comment (probably I didnt express well my english is a bit bad)

the workaround is move what you need execute with sudo to an external script, example

```bash
# ~/.scripts/sudo_uptime.sh
echo mypassword | sudo -kS uptime
```

dont forget add execution permissions to tour external script `chmod +x ~/.scripts/sudo_uptime.sh` then your argos config it'll be something like

```bash
#!/usr/bin/env bash

echo "Test"
echo "---"
echo "Run uptime with sudo | bash='~/.scripts/sudo_uptime.sh' terminal=false" 
```

I've tested this by myself and it's working fine (I enable password for my sudo)

**Comment by scoony** [comment]
You purpose and exactly what I tried in first place ;)

**Comment by scoony** [comment]
the journalctl command result in:
`janv. 29 07:21:44 Serveur-NAS org.gnome.Shell.desktop[2526]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e00028 (test.c.sh )`

**Comment by p-e-w** [comment]
Whatever the issue is here, it has nothing to do with Argos. Argos runs executable files, that's all. It doesn't care whether those files in turn invoke `sudo`, or `top`, or any other program.

The "Buggy client" warning shown above is a GTK+ bug that has been around forever, and has nothing to do with Argos either.

**Comment by bertschneider** [comment]
If someone stumbles upon this issue: At least in my case it seemed that the prompt for the password caused the problem. After setting an empty prompt with `-p ''` the script executes as expected.

```
SOMETHING=$(sudo -Sk -p '' <<< $password some_command)
echo "${SOMETHING}"
```
