### ISSUE TITLE
Where to find additional icon names?

### ISSUE THREAD

**Issue by aggsol** [p-e-w/argos#34]
The launcher example uses the icon `starred` which is not on the freedesktop.org icon naming specification list. Where can I get additional icon names?

**Comment by aggsol** [comment]
* [Standard Icon Names](https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html)
* [Gnome Icon Naming Spec](https://developer.gnome.org/icon-naming-spec/)

**Comment by scoony** [comment]
Hi

You can use any icon... even your own PNG files

**Comment by scoony** [comment]
**How to add your own icons (my way)**

- make a cache folder in your github
- create a cache folder in your local argos folder (/home/user/.config/argos/.cache-icons)
- handle them like this

```
#!/usr/bin/env bash

#### Declaration of the cache folder (and creation if missing)
icons_cache=`echo $HOME/.config/argos/.cache-icons`
if [[ ! -f "$icons_cache" ]]; then
  mkdir -p $icons_cache
fi

#### Checking if the icon is in cache (downloading if needed)
if [[ ! -f "$icons_cache/yggtorrent.png" ]] ; then curl -o "$icons_cache/yggtorrent.png" "https://raw.githubusercontent.com/scoony/yggtorrent.c.1h.sh/master/.cache-icons/yggtorrent.png" ; fi

#### Putting the local icon in variable
YGGTORRENT_ICON=$(curl -s "file://$icons_cache/yggtorrent.png" | base64 -w 0)

#### Using the icon
echo " TITLE | image='$YGGTORRENT_ICON' imageWidth=25"
```

If you've got any question, i'm here :)

**Comment by scoony** [comment]
Can they close this topic?

**Comment by aggsol** [comment]
@scoony If we leave it open, people can find the links and snippet. Maybe the content would be great in the Wiki, @p-e-w Are you interested in opening up the wiki for tips, tricks, best practices and links to plugins?

**Comment by scoony** [comment]
I'm not part of their team... dunno if I can add stuff to their wiki

**Comment by p-e-w** [comment]
All icon names available on the system can be found by running `gtk3-icon-browser`. I have added this information to the README.

I have also opened the Wiki for editing as suggested.
