### ISSUE TITLE
Trigger action with click on panel icon?

### ISSUE THREAD

**Issue by orschiro** [p-e-w/argos#38]
Hey @p-e-w,

Thanks for this extension!

The readme mentions that it's main functionality is opening and triggering actions from a dropdown menu. 

Can Argos also trigger an action from a direct click on a top panel icon/button?

Thanks!

**Comment by p-e-w** [comment]
If a [`+` is placed in the filename](https://github.com/p-e-w/argos#filename-format), Argos will refresh the plugin when the button is clicked.

I have no plans to add any other actions since the button already has the "open menu" role by default.
