### ISSUE TITLE
Fullscreen game stutters when extension refreshes

### ISSUE THREAD

**Issue by amenoko** [p-e-w/argos#39]
Hi, sorry if this might be the wrong place to post, but I've observed some weird behavior with Argos. I have a script that essentially does 'ping -c1 8.8.8.8' and I named it 'ping.1s.sh'. When it's running and I run Rocket League on my other monitor, the game stutters in sync with the extension refreshing. When I disable the extension, the stuttering goes away. I can notice the stuttering as well simply when dragging around a window. Weirdly enough from what I remember, I've been using this extension for over a week and it has only started causing this problem yesterday.

My hardware is: i7 4790k, GTX 970. I'm running Arch Linux, kernel version 4.15.8, nvidia 390.25, gnome-shell 3.26.2.

Has anybody run into a similar problem? Personally I'm fine with just disabling the extension when I don't need it but it may or may not be worth looking into.

**Comment by scoony** [comment]
An idea for a workaround:

```
check_process=`ps aux | grep "RocketLeague"`
if [[ "$RocketLeague" == "" ]]; then
  my_request=`ping -c1 8.8.8.8`
  echo "Whatever you want to display"
fi
```

**Comment by p-e-w** [comment]
Argos adds and removes panel menus using the official GNOME Shell APIs, that's all. It works the same way as all other GNOME Shell extensions that do that.

Thus any problem of this type is necessarily a bug in GNOME Shell, or the window manager, or another program.
