### ISSUE TITLE
Submit to extensions.gnome.org

### ISSUE THREAD

**Issue by p-e-w** [p-e-w/argos#4]

**Comment by vanous** [comment]
I tough i would comment here, rather then opening an issue :)
First of all, thank you!!! This is the best extension ever. Seriously!

Secondly, not much traction on HN today: https://news.ycombinator.com/item?id=13793212 , but perhaps it will catch. When BitBar is discussed, **many** people ask for Linux equivalent and Argos is more then perfect.

Now more questions please:

Is there a way to have refresh=true also on the top "icon/item", so when i click on actual item in the menu bar, the script is re-run? I trued doing this but no luck:

`#!/usr/bin/env bash`
`echo "|iconName=starred refresh=true"` **← notice here**
`echo "---"`
`echo "ScreenShot | iconName=camera-photo bash='gnome-screenshot --interactive' terminal=false"`
`sudo tlp-stat -s | grep "Power source" | awk -F" = " '{print "Running on " $2}'`


Is there a way to have some kind of menu overflow/scroll? For example the HN [plugin](https://raw.githubusercontent.com/matryer/bitbar-plugins/master/Web/HackerNews/hacker_news.1m.rb) - i have limited it to some 6 items, as it grows too big, but if it could scroll :)))

What about plugins, where is the best to submit, to BitBar or are you planning to have your own plugin repo?

Lastly, where to ask for advice like this? IRC? Forum? Here?

thank you very much!

Petr

**Comment by p-e-w** [comment]
@vanous:

> Is there a way to have refresh=true also on the top "icon/item", so when i click on actual item in the menu bar, the script is re-run?

No, for semantic reasons. The widget added to the panel is a menu button. Clicking that button opens the menu and having it do anything else in addition to that breaks a decades-old UX pattern.

However, in most cases, setting the script to auto-refresh should make this unnecessary anyway.

> Is there a way to have some kind of menu overflow/scroll?

AFAIK, GNOME Shell does not support that. Either way, this is the job of the toolkit. Argos just creates standard GNOME Shell menus and they do and should behave like all other menus on the system.

> What about plugins, where is the best to submit, to BitBar or are you planning to have your own plugin repo?

Any plugin that runs on macOS also should be submitted to BitBar because that's where most of the interested community is. If you have written a plugin that is specific to Linux, perhaps you would like to open an issue thread here where you and others can post such plugins for now. If there turn out to be many of them, perhaps moving them to an external location such as a separate repository might be considered.

> Lastly, where to ask for advice like this? IRC? Forum? Here?

I'm fine with questions simply being posted on this issue tracker.

Thank you for your interest! 👍
