### ISSUE TITLE
[Feature Request] Ayatana Application IndicatorSupport

### ISSUE THREAD

**Issue by xd1936** [p-e-w/argos#44]
This is an awesome Gnome Shell extension! It would be super awesome if it also had [Application Indicator](https://wiki.ubuntu.com/Ayatana) support so that it could work with other DEs, like on elementary os' [Wingpanel](https://github.com/elementary/wingpanel).

More docs and examples:
https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators#Vala_Example

**Comment by p-e-w** [comment]
I have no plans to implement support for other DEs. Argos is a GNOME Shell extension and works only on GNOME Shell. This is by design, because it allows Argos to focus on delivering the best possible experience for its platform.
