### ISSUE TITLE
Unable to run "top" plugin

### ISSUE THREAD

**Issue by teras** [p-e-w/argos#45]
Hello
First time Argos user here, and I am already amazed by the possibilities of this plugin... thank you!

I have  a problem though, when trying to use it. I copied & pasted the "top" plugin you have in your site, and although I clearly understand the logic, I can't seem to make it work.
It appears, when I click on it I can see the "Loading..." text, but it never refreshes, neither shows any actual information.
Am I missing something?

**Comment by Polish-Civil** [comment]
I have the same issue, it seems like it does not get refreshed

**Comment by VVhitehead** [comment]
```
#!/bin/bash

echo "top | color=#33BEFF"
echo "---"

TOP_OUTPUT=$(top -b -n 1 | head -n 20 | tr -d '[]|' | awk 1 ORS="\\\\n")
echo "$TOP_OUTPUT | font=monospace bash=top"
```
Try using ^this. About it never refreshing, I've found that 3s+ doesn't refresh either when clicking on the button or automatically after 3 seconds on my setup, so if you happen to have the same issue use top.3s.sh instead of top.3s+.sh

**Comment by garymoon** [comment]
I had the same problem. The menu open logic is new (https://github.com/p-e-w/argos/commit/af6f3591607407831cf5054359e50ff485939174), and it looks like @p-e-w hasn't submitted it for review yet. I cloned the git repo, copied the contents into `~/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/` and restarted my shell `Alt+F2 r. All works perfectly now!

Thanks for a really great plugin @p-e-w!!

**Comment by teras** [comment]
Indeed, if I fork this repository, top works as expected

**Comment by teras** [comment]
At least thank you for this plugins which makes halves of my other plugins
obsolete 😊

Στις Σάβ, 12 Μαΐ 2018, 12:21 μ.μ. ο χρήστης Philipp Emanuel Weidmann <
notifications@github.com> έγραψε:

**Comment by garymoon** [comment]
@p-e-w Sorry mate, I didn't mean to imply you were being lax or anything (Argos is actually _amazing_). I did check the review queue before I said what I said (because yeah that thing is in a _sorry_ state) and must have had a boy's look as my mum would say :(
