### ISSUE TITLE
Removing script name and file shortcut from bottom of menu.

### ISSUE THREAD

**Issue by ukulanne** [p-e-w/argos#46]
Is there a way to remove the last entry with the shortcut to the script that appears at the bottom of the menu? Something like ARGOS_SHOW_SCRIPT. Also something like ARGOS_SHOW_SCRIPT_NAME to be able to change the name of the script shown if it is desired to keep it.

**Comment by teras** [comment]
I'd double that, or at lease minimize the screen space that reserves the separator and the filename indicator

**Comment by p-e-w** [comment]
Duplicate of #35.
