### ISSUE TITLE
can't seem to get scripts to run [ubuntu 18.04]

### ISSUE THREAD

**Issue by arooni** [p-e-w/argos#47]
i tried the example in your helpful documentation, but all i see is ... I tried to upload an example.

if i select it it just loads the the script that it describes. (but still can't get output going). ideas?

![screenshot from 2018-05-26 17-18-31](https://user-images.githubusercontent.com/556667/40580683-1dd7875c-6109-11e8-9335-891584bb0e7e.png)

**Comment by p-e-w** [comment]
> i tried the example in your helpful documentation

Which example? There are four of them...

Do you have the latest version of Argos?

**Comment by arooni** [comment]
got it working !  closing.  i think it was just due to conflicting gnome shell extensions
