### ISSUE TITLE
Hide an indicator

### ISSUE THREAD

**Issue by memeplex** [p-e-w/argos#49]
Maybe this is possible but I'm not able to see how.

My use case is to show an indicator when some kind of activity is happening (dropbox is syncing) but removing the indicator altogether otherwise. Nevertheless returning "|" or " " leaves a blank space in the bar and returning an empty line shows the name of the script. So I don't know how to suppress the indicator when unneeded, if that's possible at all.

**Comment by p-e-w** [comment]
Implemented by @matthias-g in #54.
