### ISSUE TITLE
Question about the bitbar stock ticker

### ISSUE THREAD

**Issue by GrouchyGaijin** [p-e-w/argos#5]
Hi Guys,

I am running GNOME Shell 3.18.5

I actually have a couple of questions.
**1.** The Bitbar Stock Ticker plugin is working on my Ubuntu 16.04 system, but looking at the python code (which I freely admit I know very little about) it _looks_ like there is supposed to be a scrolling ticker of stock symbols.  Is it possible to have a scrolling ticker move across the desktop?

**2.** My second question is, as you can see in the screen shot, I have no icon or title for the stock ticker.  What could be the reason that a title, like Google Finance Stock Ticker does not appear in my panel?  Is there a way to make a title appear?

I am also curious as to why there is no title for my basic launcher, although I did get an icon to appear.
![running-on-ubuntu-16 04-gnome-shell](https://cloud.githubusercontent.com/assets/4334190/23591465/336ea020-01ae-11e7-9f5a-56df9c76a2fa.png)

Thank you,

GG

**Comment by p-e-w** [comment]
Indeed something strange is going on here. Could you provide more details about your setup? I see what appear to be a nonstandard Shell theme and several other extensions.

It looks like there might simply not be enough horizontal space for the menu buttons to expand and show the title. You could test this by renaming `stocks.py` to `stocks.c..py` (note the two successive dots) to move the button to the left of the clock where it should have more breathing room, or by disabling some of the other extensions.

Note also that if the name of the script is `stocks.py`, it will not update at regular intervals. To have a practical stock ticker you probably want `stocks.5m.py` or something similar.

**Comment by GrouchyGaijin** [comment]
Thank you so much.
I cleaned out some of the extensions that I had not really used in a long while and now things appear as they should.
I did rename `stocks.py` to `stocks.5m.py`.  I am guessing the 5m tells the script to run every five minutes?
I experimented with the `..` a bit, but was unable to move the stock quotes to the left of the clock.
Should that be `stocks.5m..py`?

Thanks again, this really fills a need I have.

GG

**Comment by p-e-w** [comment]
> I experimented with the .. a bit, but was unable to move the stock quotes to the left of the clock.
Should that be stocks.5m..py?

No, `stocks.c..py` is correct, as documented in the README. If it isn't working for you, I suspect there might again be other extensions interfering. Unfortunately, there is no way to prevent this in general, as GNOME Shell extensions are essentially monkey-patches and not isolated from each other at all.
