### ISSUE TITLE
Dropbox example

### ISSUE THREAD

**Issue by memeplex** [p-e-w/argos#50]
I would like to contribute this super simple example that I find very useful as a substitute for the (now unsupported) dropbox systray icon:

```
#!/usr/bin/env bash

case $(dropbox-cli status) in
    "Up to date") echo "| iconName=dropboxstatus-idle" ;;
    "Syncing"*)   echo "| iconName=dropboxstatus-busy"
		  echo "| iconName=dropboxstatus-busy2" ;;
    *)            echo "| iconName=dropboxstatus-x" ;;
esac
```

Save it as `dropbox.6s.sh` and voila.

**Comment by p-e-w** [comment]
Cool! Feel free to add this to the Wiki.

**Comment by memeplex** [comment]
Done https://github.com/p-e-w/argos/wiki/Dropbox-Client.
