### ISSUE TITLE
Update after executing

### ISSUE THREAD

**Issue by smathieson** [p-e-w/argos#55]
Hello,

First off thanks for argos, its great!

I was wondering if you could put another interval option, for example ++ or some other bit for the name, whereby if an action is executed then the icon should update. I have a "settings" icon that shows various states, this I have updating every few seconds, would be much better if it only updated when something is executed.

Thanks again!

**Comment by p-e-w** [comment]
This already exists, in the form of the `refresh` action attribute :)
