### ISSUE TITLE
Displaying strings containing '&'

### ISSUE THREAD

**Issue by Skillzore** [p-e-w/argos#62]
Trying to display a string containing '&' does not work. (Song title from Spotify if anyone is wondering).
A script containing
`echo "a & b"`
works fine in terminal, but displays nothing in the top bar with Argos.

I did not find anything in this issue section or on google regarding this. I am sorry if I missed anything and asked an already answered question.

**Comment by Odyseus** [comment]
Hello, @Skillzore.

You can use an [HTML entity name or number](https://www.w3schools.com/html/html_entities.asp) (`echo "a &amp; b"` or `echo "a &#38; b"`).

**Comment by Skillzore** [comment]
Great thanks!

**Comment by Skillzore** [comment]
@Odyseus A similar issue regarding "|", running script in terminal gives the vertical line, but not in the top bar. Everything behind the vertical line is not displayed and the html "&vert;" does not seem to work.

**Comment by Skillzore** [comment]
Found it! It is `&#124`.
Reference: https://www.w3schools.com/html/html_charset.asp
