### ISSUE TITLE
Arbitrary icon

### ISSUE THREAD

**Issue by Chrismarsh** [p-e-w/argos#63]
It would be nice to use arbitrary icons. `iconName` doesn't seem to support this. Is this possible?

**Comment by p-e-w** [comment]
Yes, using the `image` attribute, as documented in the README.

The "Simple launcher" example in the README shows how to use it.

**Comment by Chrismarsh** [comment]
@p-e-w My sincere apologizes. I have no idea how I missed that. Works like a charm.
