### ISSUE TITLE
refresh=true should run after bash=command finishes

### ISSUE THREAD

**Issue by iexos** [p-e-w/argos#7]
Not sure if it is by design or not, but it would be really useful if the script would reload after the command has finished to reflect the changes made by pressing the button (modifying a file in my case).

To quote the BitBar documentation:

> `refresh=..` to make the item refresh the plugin it belongs to. If the item runs a script, refresh is performed after the script finishes. eg. `refresh=true`

Test with this plugin and click on "Test delay" (on my machine output is 0.01):
```
#!/usr/bin/sh

FILE="/home/user/testfile"

echo "`cat $FILE`"
echo "---"
echo "Test delay | bash='echo 0.00 > $FILE; sleep 0.01; echo 0.01 > $FILE; sleep 0.05; echo 0.05 > $FILE' terminal=false refresh=true"
```

**Comment by p-e-w** [comment]
Marking this as a bug as it deviates from the BitBar specification.

**Comment by nsrosenqvist** [comment]
I would like to be able to refresh the plugin every time it's opened as mine displays the status of a couple of operations. If I set refresh=true on the top line-item it doesn't change anything

**Comment by nsrosenqvist** [comment]
I found this as a workaround: https://github.com/p-e-w/argos/issues/17#issuecomment-294844734

**Comment by p-e-w** [comment]
This is now fixed on master.
