### ISSUE TITLE
Disable autogenerated last menu entry

### ISSUE THREAD

**Issue by nis65** [p-e-w/argos#71]
Hi Philipp

first thanks for such an easy to use extension. I was looking for a method to disable the generation of the menu item that opens the script in an editor. While this item is extremely convenient while developing, I would not like to have this in the configuration of my father's desktop :-) 

I hacked (ugly, but does the trick):

```
--- ../button.js        2018-04-08 08:46:11.000000000 +0200
+++ ./button.js 2019-01-10 20:51:59.159574262 +0100
@@ -207,6 +207,6 @@
     menuItem.connect("activate", Lang.bind(this, function() {
       Gio.AppInfo.launch_default_for_uri("file://" + this._file.get_path(), null);
     }));
-    this.menu.addMenuItem(menuItem);
+    // this.menu.addMenuItem(menuItem);
   }
 });
```

**Comment by p-e-w** [comment]
This has been requested many times (see #46 and #35 for some previous discussions) but I have decided not to implement it. Argos doesn't really have a "configuration". I consider this a strength in general, but it also means that not every knob can be tweaked.

**Comment by nis65** [comment]
Thanks for your extremely quick answer and the links. I understand your rationale - and if someone really wants it, it can be hacked. It's FOSS :-)

**Comment by maribote** [comment]
Thank you @nis65 for this! I for one don't understand @p-e-w 's rationale. That Argos configuration resides in the file name is something that can be communicated to the user in the documentation of Argos and of each extension. Providing the user with a direct access to the source code of the script doesn't seem to be needed or desirable at all. I'm glad I can now have my metric clock with no drop-down menu ;-).
