### ISSUE TITLE
Shell crashes when writing to file in config directory

### ISSUE THREAD

**Issue by matthias-g** [p-e-w/argos#78]
Using the following plugin the GNOME Shell crashes when clicking on 'Test'

```bash
#!/usr/bin/env bash

echo "Crash Test"

echo "---"
echo "Test | bash='echo test > ~/.config/argos/test.tmp' terminal=false"
```
I'm running GNOME Shell 3.32.1 and the most current Argos version.

**Comment by matthias-g** [comment]
As this is probably not a bug in Argos (an extension should not be able to cause crashes of the GNOME shell), I've submitted an issue here: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1229

**Comment by p-e-w** [comment]
As mentioned in the linked GNOME bug, this was caused by the incompatibility with GNOME Shell 3.32, which has since been fixed.
