### ISSUE TITLE
no way to refresh when command failed

### ISSUE THREAD

**Issue by lidaobing** [p-e-w/argos#83]
when there is no network, my command will failed, but I can not tell argos to re-run the script when network is ready. the only workaround is disable and enable argos through gnome-tweak.

**Comment by p-e-w** [comment]
Argos re-runs scripts whenever they are modified (this is what makes the live-reload feature work). Therefore, to programmatically refresh a script, you only need to make any change to it on disk.

For example, you can try `touch`, or if that doesn't work, append a newline to the end of the script file or similar.
