### ISSUE TITLE
object.actor is deprecated

### ISSUE THREAD

**Issue by hashstat** [p-e-w/argos#96]
I recently upgraded to gnome-shell 3.34 on Arch Linux and just noticed that I am getting warnings in the system journal whenever Argos updates:

```
Oct 01 09:00:25 abcde gnome-shell[37594]: Usage of object.actor is deprecated for ArgosButton
                                          get@resource:///org/gnome/shell/ui/environment.js:242:29
                                          _processOutput@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:139:5
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          _update/<@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:95:11
                                          spawnWithCallback/<@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:268:7
                                          readStream/<@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:280:7
Oct 01 09:00:25 abcde gnome-shell[37594]: Usage of object.actor is deprecated for ArgosButton
                                          get@resource:///org/gnome/shell/ui/environment.js:242:29
                                          _processOutput@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:141:9
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          _update/<@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:95:11
                                          spawnWithCallback/<@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:268:7
                                          readStream/<@/home/user/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:280:7
```

Being a gnome-shell extension developer must be tough because it seems that with every release the developers introduce breaking changes. I know it frustrates me as a consumer of the extensions. But thanks for this cool extension.

**Comment by plegrand1** [comment]
Same problem here. Debian SID - gnome-shell 3.34

**Comment by pszafer** [comment]
I changed those lines https://github.com/p-e-w/argos/blob/e7c69ff02c63512b5de5b68b5bcaee547d11dc3a/argos%40pew.worldwidemann.com/button.js#L139 
to somethink like this:
```
let actor_visible = buttonLines.length > 0 || !dropdownMode;
if (!actor_visible)
   return;
```

not sure what is does though, but argos is working for me and error is not present.

**Comment by 73** [comment]
> I changed those lines
> 
> https://github.com/p-e-w/argos/blob/e7c69ff02c63512b5de5b68b5bcaee547d11dc3a/argos%40pew.worldwidemann.com/button.js#L139
> 
> to somethink like this:
> 
> ```
> let actor_visible = buttonLines.length > 0 || !dropdownMode;
> if (!actor_visible)
>    return;
> ```
> 
> not sure what is does though, but argos is working for me and error is not present.

Issue is present on ubuntu 19.10.
However, the change proposed render argos not functional.

**Comment by ElijahLynn** [comment]
Getting this error just hammering my logs too. Makes it difficult to read. FWIW, my argos scripts are working fine.

**Comment by ElijahLynn** [comment]
Thank you @p-e-w!
